services:
  - docker

before_install:
  - docker build --tag roblobob/docker-ci-workflow1 -f Dockerfile.dev .

script:
  - docker run --rm -e CI=true roblobob/docker-ci-workflow1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-ci-workflow1"
  env: "DockerCiWorkflow1-env"
  bucket_name: "elasticbeanstalk-eu-west-2-380631270758"
  bucket_path: "docker-ci-workflow1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
