sudo: required
services:
  - docker

before_install:
  - docker build --tag roblobob/docker-ci-workflow1 -f Dockerfile.dev .

script:
  - docker run --rm -e CI=true roblobob/docker-ci-workflow1 npm run test
